### ISSUE TITLE
Encoding Issues

### ISSUE THREAD

**Issue by ldacey** [domoinc/domo-python-sdk#11]
I am receiving some encoding issues on certain characters when using the Python API (which is awesome by the way, thanks so much!), but the same data sent through workbench does not have any errors.

```
datablock = datablock.encode("iso-8859-1")
UnicodeEncodeError: 'latin-1' codec can't encode character '\u0160' in position 5104: ordinal not in range(256)
```
Some other ones which did not work are below are '\u2013', '\u2019', '\u2018'. In all cases, my workaround was to loop through my dimension columns and replace the characters with blanks or something similar.

df[column] .str.encode('utf-8')
Do some replacements and then
df[column] .str.decode('latin-1')

Mainly raising this as an issue just because Workbench seems to handle it fine and the data gets imported to Domo with no errors.

**Comment by rswingler** [comment]
I'm glad you're enjoying the SDK! I'll dig into this right away, and a few things come to mind immediately:

- Are you running your python scripts with Python3? (ie "python3 myFile.py")? Python3 supports unicode by default, whereas Python2 supports ASCII and unicode strings must be wrapped in the "unicode()" function: https://docs.python.org/2/howto/unicode.html

- Is your windows console encoding set correctly? Python execution may fail if unable to print special characters to the windows console: https://wiki.python.org/moin/PrintFails

Other than that, I'll see if I can replicate the issue. What's your SDK version, as well as python and command prompt versions?

**Comment by yunruiwatts** [comment]
This sounds like the issue I fixed with commit bcbac16693c702b10203c087046dbd4817c8839d. If you aren't on pydomo version 0.2, you can run `pip install -U pydomo` to get the latest version of the SDK. Do note that there are some minor breaking changes with upgrading to 0.2 - API calls now accept and return dictionaries. For example, when getting a dataset's information, you would now use `dataset['name']` instead of `dataset.name`.

**Comment by ldacey** [comment]
Hi - yes I am using Python 3 and all data is being processed on a Linux server (I query for the data with pandas, write it to stringio, and send that file object to Domo). 

99% of all of the data I deal with is in UTF-8 (I explicitly convert it before loading it to our database). This particular data source is something which is saved as CP1252 (it is from MS SQL server, but then gets modified in Excel by some other teams which is where some of these weird characters are introduced).

My current version 1.3, so I will upgrade ASAP
pydomo==0.1.3

**Comment by ldacey** [comment]
I upgraded pydomo and tested it again (without replacing any characters):

```
def save_to_domo(domo_id, query, **kwargs):
    domo = Domo(DOMO_CLIENT, DOMO_SECRET, DOMO_API, use_https=True, logger_name='domo', logger_level=logging.ERROR)
    streams = domo.streams
    csv = StringIO()
    df = pd.read_sql(query, con=DATABASE.get_conn())
    df.to_csv(csv, index=False, sep=',', compression='gzip', encoding='utf-8')
    csv.seek(0)
    part = 1
    execution = streams.create_execution(domo_id)
    streams.upload_part(domo_id, execution['id'], part, csv)
    committed_execution = streams.commit_execution(domo_id, execution['id'])
```

UnicodeEncodeError: 'latin-1' codec can't encode character '\u0160' in position 4260: ordinal not in range(256)

**Comment by yunruiwatts** [comment]
@ldacey Can you post more of the stack trace? In particular, which line of your `save_to_domo` method did it fail on?

**Comment by yunruiwatts** [comment]
@ldacey is this a problem for you any more?

**Comment by ldacey** [comment]
Yes, it is. An error report from earlier is below.

My solution is to just loop through the columns remove the non ascii characters. This does change the value though, but most of these columns are not meant to be joined on anyway. The only issue is when I don't realize that there are characters like this in the data in advance. 

The cause of the problems is because some of the dimension tables I receive were created in Excel originally and have some non-standard characters. Some common ones are the a double dash, and a single quote character, etc (u'\u2013', u'\u2019', '\u2018' are specific ones I have run into).

`df[column] = (df[column].str.encode('ascii', 'ignore').str.decode('latin-1'))`

For some reason, using Workbench on the same data does not raise any errors.

```
[2017-12-29 12:03:12,273] INFO - Subtask: Traceback (most recent call last):
[2017-12-29 12:03:12,273] INFO - Subtask:   File "/envs/airflow_env/bin/airflow", line 28, in <module>
[2017-12-29 12:03:12,273] INFO - Subtask:     args.func(args)
[2017-12-29 12:03:12,274] INFO - Subtask:   File "/envs/airflow_env/lib/python3.6/site-packages/airflow/bin/cli.py", line 422, in run
[2017-12-29 12:03:12,274] INFO - Subtask:     pool=args.pool,
[2017-12-29 12:03:12,274] INFO - Subtask:   File "/envs/airflow_env/lib/python3.6/site-packages/airflow/utils/db.py", line 53, in wrapper
[2017-12-29 12:03:12,274] INFO - Subtask:     result = func(*args, **kwargs)
[2017-12-29 12:03:12,274] INFO - Subtask:   File "/envs/airflow_env/lib/python3.6/site-packages/airflow/models.py", line 1390, in run
[2017-12-29 12:03:12,274] INFO - Subtask:     result = task_copy.execute(context=context)
[2017-12-29 12:03:12,274] INFO - Subtask:   File "/envs/airflow_env/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 80, in execute
[2017-12-29 12:03:12,274] INFO - Subtask:     return_value = self.python_callable(*self.op_args, **self.op_kwargs)
[2017-12-29 12:03:12,274] INFO - Subtask:   File "/mnt/data-1TB/var/airflow/dags/bin/godaddy/godaddy_telephony_agent_dag.py", line 382, in send_domo_part
[2017-12-29 12:03:12,274] INFO - Subtask:     streams.upload_part(stream_id=domo_stream_id, execution_id=execution_id, part_num=part, csv=data)
[2017-12-29 12:03:12,274] INFO - Subtask:   File "/envs/airflow_env/lib/python3.6/site-packages/pydomo/streams/StreamClient.py", line 108, in upload_part
[2017-12-29 12:03:12,274] INFO - Subtask:     return self._upload_csv(url, requests.codes.ok, csv, desc)
[2017-12-29 12:03:12,274] INFO - Subtask:   File "/envs/airflow_env/lib/python3.6/site-packages/pydomo/DomoAPIClient.py", line 74, in _upload_csv
[2017-12-29 12:03:12,274] INFO - Subtask:     response = self.transport.put_csv(url=url, body=csv)
[2017-12-29 12:03:12,274] INFO - Subtask:   File "/envs/airflow_env/lib/python3.6/site-packages/pydomo/Transport.py", line 51, in put_csv
[2017-12-29 12:03:12,274] INFO - Subtask:     return self.request(url, HTTPMethod.PUT, headers, {}, body)
[2017-12-29 12:03:12,274] INFO - Subtask:   File "/envs/airflow_env/lib/python3.6/site-packages/pydomo/Transport.py", line 68, in request
[2017-12-29 12:03:12,275] INFO - Subtask:     response = requests.request(**request_args)
[2017-12-29 12:03:12,275] INFO - Subtask:   File "/envs/airflow_env/lib/python3.6/site-packages/requests/api.py", line 58, in request
[2017-12-29 12:03:12,275] INFO - Subtask:     return session.request(method=method, url=url, **kwargs)
[2017-12-29 12:03:12,275] INFO - Subtask:   File "/envs/airflow_env/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
[2017-12-29 12:03:12,275] INFO - Subtask:     resp = self.send(prep, **send_kwargs)
[2017-12-29 12:03:12,275] INFO - Subtask:   File "/envs/airflow_env/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
[2017-12-29 12:03:12,275] INFO - Subtask:     r = adapter.send(request, **kwargs)
[2017-12-29 12:03:12,275] INFO - Subtask:   File "/envs/airflow_env/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
[2017-12-29 12:03:12,275] INFO - Subtask:     timeout=timeout
[2017-12-29 12:03:12,275] INFO - Subtask:   File "/envs/airflow_env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
[2017-12-29 12:03:12,275] INFO - Subtask:     chunked=chunked)
[2017-12-29 12:03:12,275] INFO - Subtask:   File "/envs/airflow_env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
[2017-12-29 12:03:12,275] INFO - Subtask:     conn.request(method, url, **httplib_request_kw)
[2017-12-29 12:03:12,275] INFO - Subtask:   File "/envs/airflow_env/lib/python3.6/http/client.py", line 1239, in request
[2017-12-29 12:03:12,275] INFO - Subtask:     self._send_request(method, url, body, headers, encode_chunked)
[2017-12-29 12:03:12,275] INFO - Subtask:   File "/envs/airflow_env/lib/python3.6/http/client.py", line 1285, in _send_request
[2017-12-29 12:03:12,276] INFO - Subtask:     self.endheaders(body, encode_chunked=encode_chunked)
[2017-12-29 12:03:12,276] INFO - Subtask:   File "/envs/airflow_env/lib/python3.6/http/client.py", line 1234, in endheaders
[2017-12-29 12:03:12,276] INFO - Subtask:     self._send_output(message_body, encode_chunked=encode_chunked)
[2017-12-29 12:03:12,276] INFO - Subtask:   File "/envs/airflow_env/lib/python3.6/http/client.py", line 1055, in _send_output
[2017-12-29 12:03:12,276] INFO - Subtask:     for chunk in chunks:
[2017-12-29 12:03:12,276] INFO - Subtask:   File "/envs/airflow_env/lib/python3.6/http/client.py", line 1014, in _read_readable
[2017-12-29 12:03:12,276] INFO - Subtask:     datablock = datablock.encode("iso-8859-1")
[2017-12-29 12:03:12,276] INFO - Subtask: UnicodeEncodeError: 'latin-1' codec can't encode character '\u2019' in position 7716: ordinal not in range(256)
```

**Comment by yunruiwatts** [comment]
Should be fixed by eb0ab20cce5c1f454623ecc5e64bf41272891b8c - I believe it was the same issue as the one I fixed earlier, but this time it was in the StreamClient.

**Comment by ldacey** [comment]
I just updated pydomo which fixed the encoding issues I was experiencing. In case anyone else is sending data from a pandas dataframe to Domo:

Installing collected packages: pydomo
  Found existing installation: pydomo 0.2.0
    Uninstalling pydomo-0.2.0:
      Successfully uninstalled pydomo-0.2.0
Successfully installed pydomo-0.2.2.1

This code broke (which has worked previously):

```
    csv = StringIO()
    df.to_csv(csv, index=False, sep=',', compression='gzip')
    **csv.seek(0)**
    execution = streams.create_execution(domo_stream_id)
    part = 1
    streams.upload_part(domo_stream_id, execution['id'], part, csv)
```

Returns:


```
/opt/anaconda/anaconda3/envs/airflow_env/lib/python3.6/site-packages/pydomo/streams/StreamClient.py in upload_part(self, stream_id, execution_id, part_num, csv)
    106         url = self._base(stream_id) + '/executions/' + str(execution_id) + '/part/' + str(part_num)
    107         desc = "Data Part on Execution " + str(execution_id) + " on Stream " + str(stream_id)
--> 108         return self._upload_csv(url, requests.codes.ok, str.encode(csv), desc)
    109 
    110     """

TypeError: descriptor 'encode' requires a 'str' object but received a '_io.StringIO'
```

I altered the code to the following and it works:

```
    csv = StringIO()
    df.to_csv(csv, index=False, sep=',', compression='gzip')
    execution = streams.create_execution(domo_stream_id)
    part = 1
    streams.upload_part(domo_stream_id, execution['id'], part, **csv.getvalue()**)
    committed_execution = streams.commit_execution(domo_stream_id, execution['id'])
```
